=== Jabro/Yet-Another-Calendar/Yet-Another-Calendar/src/main/webapp/Resources/calendar.dtd
<!ELEMENT calendar (year)+>
<!ELEMENT year (month)+>
<!ELEMENT month (week)+>
<!ELEMENT week (day)+>
<!ELEMENT day (entry)*>
<!ELEMENT entry (summary, starttime, endtime, duration, startdate, enddate, location, description, created, modified, comment, categories, rRule)>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT starttime (#PCDATA)>
<!ELEMENT endtime (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT created (#PCDATA)>
<!ELEMENT modified (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT categories (category)*>
<!ELEMENT category (#PCDATA)>

<!ATTLIST calendar selectedyear NMTOKEN #REQUIRED selectedmonth NMTOKEN #REQUIRED selectedweek NMTOKEN #REQUIRED selectedday NMTOKEN #REQUIRED>
<!ATTLIST year number NMTOKEN #REQUIRED>
<!ATTLIST month number NMTOKEN #REQUIRED name NMTOKEN #REQUIRED>
<!ATTLIST week number NMTOKEN #REQUIRED>
<!ATTLIST day number NMTOKEN #REQUIRED name NMTOKEN #REQUIRED columns NMTOKEN #IMPLIED>
<!ATTLIST entry id NMTOKEN #REQUIRED priority NMTOKEN #IMPLIED color CDATA #IMPLIED column NMTOKEN #IMPLIED>
<!ATTLIST starttime hours NMTOKEN #REQUIRED minutes NMTOKEN #REQUIRED>
<!ATTLIST endtime hours NMTOKEN #REQUIRED minutes NMTOKEN #REQUIRED>
<!ATTLIST duration hours NMTOKEN #REQUIRED minutes NMTOKEN #REQUIRED>
<!ATTLIST created day NMTOKEN #REQUIRED month NMTOKEN #REQUIRED year NMTOKEN #REQUIRED hours NMTOKEN #REQUIRED minutes NMTOKEN #REQUIRED>
<!ATTLIST modified day NMTOKEN #REQUIRED month NMTOKEN #REQUIRED year NMTOKEN #REQUIRED hours NMTOKEN #REQUIRED minutes NMTOKEN #REQUIRED>
<!ATTLIST startdate day NMTOKEN #REQUIRED month NMTOKEN #REQUIRED year NMTOKEN #REQUIRED hours NMTOKEN #REQUIRED minutes NMTOKEN #REQUIRED>
<!ATTLIST enddate day NMTOKEN #REQUIRED month NMTOKEN #REQUIRED year NMTOKEN #REQUIRED hours NMTOKEN #REQUIRED minutes NMTOKEN #REQUIRED>

=== Jabro/Yet-Another-Calendar/Yet-Another-Calendar/resources/calender_yearview.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE calendar SYSTEM "Resources/calendar.dtd">

<?xml-stylesheet type="text/xsl" href="Resources/calendar_yearview.xsl"?>
<calendar selectedyear="2012" selectedmonth="0" selectedweek="0" selectedday="0">
  <year number="2012">
    <month name="Jan" number="1">
      <week number="1">
        <day name="Mo" number="1">
          <entry id="1" priority="high" color="#FFFF">
            <summary>Hammer Job</summary>
            <starttime hours="9" minutes="44" />
            <endtime hours="9" minutes="44" />
            <duration hours="9" minutes="44" />
            <location>KA</location>
            <description>Teeeest</description>
            <created day="19" month="5" year="2012" hours="9" minutes="44" />
            <modified day="19" month="5" year="2012" hours="9" minutes="44" />
            <comment>Hoffentlich klappts</comment>
            <categories>
              <category>Cate1</category>
              <category>Cate2</category>
              <category>Cate3</category>
            </categories>
          </entry>
        </day>
      </week>
    </month>
    <month name="Feb" number="2">
      <week number="1">
        <day name="Mo" number="1">
          <entry id="1" priority="high" color="#FFFF">
            <summary>Hammer Job</summary>
            <starttime hours="9" minutes="44" />
            <endtime hours="9" minutes="44" />
            <duration hours="9" minutes="44" />
            <location>KA</location>
            <description>Teeeest</description>
            <created day="19" month="5" year="2012" hours="9" minutes="44" />
            <modified day="19" month="5" year="2012" hours="9" minutes="44" />
            <comment>Hoffentlich klappts</comment>
            <categories>
              <category>Cate1</category>
              <category>Cate2</category>
              <category>Cate3</category>
            </categories>
          </entry>
        </day>
      </week>
    </month>
  </year>
</calendar>

=== Jabro/Yet-Another-Calendar/Yet-Another-Calendar/src/main/webapp/calendar_monthview.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE calendar SYSTEM "Resources/calendar.dtd">
<?xml-stylesheet type="text/xsl" href="Resources/calendar_monthview.xsl" ?>
<calendar selectedyear="2012" selectedmonth="2" selectedweek="6" selectedday="12">
	<year number="2012">
		<month name="Mar" number="3">
			<week number="1">
				<day name="Mo" number="28"/>
				<day name="Di" number="29"/>
				<day name="Mi" number="30"/>
				<day name="Do" number="31"/>
			</week>
		</month>
		<month name="Apr" number="4">
			<week number="1">
				<day name="Fr" number="1">
					<entry id="523jhls2" priority="high" color="#000">
						<summary>Kaffee</summary>
						<starttime hours="16" minutes="00"/>
						<endtime   hours="20" minutes="00"/>
						<duration  hours="4"  minutes="0"/>
						<location>SAP Coffeecorner</location>
						<description>Test1</description>
						<created  day="12" month="03" year="1920" hours="12" minutes="30"/>
						<modified day="12" month="03" year="1920" hours="12" minutes="30"/>
						<comment>text</comment>
						<categories>
							<category>test1</category>
							<category>test1</category>
						</categories>
					</entry>
					<entry id="23kh234" priority="high" color="#000">
						<summary>Projektbesprechung</summary>
						<starttime hours="16" minutes="00"/>
						<endtime   hours="20" minutes="00"/>
						<duration  hours="4"  minutes="0"/>
						<location>DHBW</location>
						<description>Test3</description>
						<created  day="12" month="03" year="1920" hours="12" minutes="30"/>
						<modified day="12" month="03" year="1920" hours="12" minutes="30"/>
						<comment>text</comment>
						<categories>
							<category>test3</category>
							<category>test3</category>
						</categories>
					</entry>
				</day>
				<day name="Sa" number="2">
					<entry id="1" daycount="2">
					<summary>Test2</summary>
						<starttime hours="16" minutes="00"/>
						<endtime   hours="20" minutes="00"/>
						<duration  hours="4"  minutes="0"/>
						<location>Test1</location>
						<description>Test2</description>
						<created  day="12" month="03" year="1920" hours="12" minutes="30"/>
						<modified day="12" month="03" year="1920" hours="12" minutes="30"/>
						<comment>text</comment>
						<categories>
							<category>test1</category>
							<category>test1</category>
						</categories>
					</entry>
				</day>
				<day name="So" number="3"/>
				<day name="Mo" number="4"/>
				<day name="Di" number="5"/>
				<day name="Mi" number="6"/>
				<day name="Do" number="7"/>
			</week>
			<week number="2">
				<day name="Fr" number="8"/>
				<day name="Sa" number="9"/>
				<day name="So" number="10"/>
				<day name="Mo" number="11"/>
				<day name="Di" number="12"/>
				<day name="Mi" number="13"/>
				<day name="Do" number="14"/>
			</week>
			<week number="2">
				<day name="Fr" number="15"/>
				<day name="Sa" number="16"/>
				<day name="So" number="17">
				</day>
				<day name="Mo" number="18"/>
				<day name="Di" number="19"/>
				<day name="Mi" number="20"/>
				<day name="Do" number="21"/>
			</week>
			<week number="2">
				<day name="Fr" number="22"/>
				<day name="Sa" number="23"/>
				<day name="So" number="24"/>
				<day name="Mo" number="25"/>
				<day name="Di" number="26"/>
				<day name="Mi" number="27"/>
				<day name="Do" number="28"/>
			</week>
			<week number="2">
				<day name="Fr" number="29"/>
				<day name="Sa" number="30"/>
			</week>
		</month>
		<month name="May" number="5">
			<week number="1">
				<day name="So" number="1"/>
			</week>
		</month>
	</year>
</calendar>
